# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionchoiceplayer',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
